# Generated by Django 4.2.1 on 2023-07-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('DEPTNO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('DNAME', models.CharField(max_length=50)),
                ('LOC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EMPNO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ENAME', models.CharField(max_length=50)),
                ('JOB', models.CharField(max_length=50)),
                ('SAL', models.PositiveIntegerField()),
                ('DEPTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
